map_exercises = {
    0: "Decline Push-ups",
    1: "Bear Crawls",
    2: "Dips",
    3: "Mountain Climbers",
    4: "Bicep Curls",
    5: "Leg Press",
    6: "Thrusters",
    7: "Turkish Get-ups",
    8: "Glute Bridges",
    9: "Step-ups",
    10: "Plank",
    11: "Pull-ups",
    12: "Lunges",
    13: "Plyo Squats",
    14: "Squats",
    15: "Frog Jumps",
    16: "Deadlifts",
    17: "Prone Cobras",
    18: "Lat Pulldowns",
    19: "Russian Twists",
    20: "Shoulder Press",
    21: "Tricep Dips",
    22: "Kettlebell Swings",
    23: "Resistance Band Pull-Aparts",
    24: "Leg Raises",
    25: "Tricep Extensions",
    26: "Dead Bugs",
    27: "Scissors Kicks",
    28: "Plyometric Push-ups",
    29: "Push Ups",
    30: "Bench Press",
    31: "Inverted Rows",
    32: "Seated Rows",
    33: "Calf Raises",
    34: "Reverse Lunges",
    35: "Deadlift",
    36: "Wall Angels",
    37: "Lateral Raises",
    38: "Face Pulls",
    39: "Burpees",
    40: "Push-ups",
    41: "Box Jumps",
    42: "Rows",
    43: "Bird Dogs",
    44: "Dragon Flags",
    45: "Bicycle Crunches",
    46: "Flutter Kicks",
    47: "Bulgarian Split Squats",
    48: "Superman",
    49: "Incline Push-ups",
    50: "Jumping Jacks",
    51: "Renegade Rows",
    52: "Windshield Wipers",
    53: "Zottman Curls",
    54: "Pistol Squats",
}

CATEGORICAL_COLS = [
    "Gender",
    "diet_type",
    "cooking_method",
    "Equipment Needed",
    "Difficulty Level",
    "Body Part",
]

NUMERICAL_COLS = [
    "Age",
    "Water_Intake (liters)",
    "Height (m)",
    "Weight (kg)",
    "Session_Duration (hours)",
    "Workout_Frequency (days/week)",
    "Experience_Level",
    "Daily meals frequency",
]

TARGET_COL = "Name of Exercise"

model_params = {
    "objective": "multi:softmax",
    "base_score": None,
    "booster": None,
    "callbacks": None,
    "colsample_bylevel": None,
    "colsample_bynode": None,
    "colsample_bytree": None,
    "device": None,
    "early_stopping_rounds": None,
    "enable_categorical": False,
    "eval_metric": "mlogloss",
    "feature_types": None,
    "feature_weights": None,
    "gamma": None,
    "grow_policy": None,
    "importance_type": None,
    "interaction_constraints": None,
    "learning_rate": 0.2,
    "max_bin": None,
    "max_cat_threshold": None,
    "max_cat_to_onehot": None,
    "max_delta_step": None,
    "max_depth": 7,
    "max_leaves": None,
    "min_child_weight": None,
    "missing": None,
    "monotone_constraints": None,
    "multi_strategy": None,
    "n_estimators": 150,
    "n_jobs": None,
    "num_parallel_tree": None,
    "random_state": None,
    "reg_alpha": None,
    "reg_lambda": None,
    "sampling_method": None,
    "scale_pos_weight": None,
    "subsample": None,
    "tree_method": None,
    "validate_parameters": None,
    "verbosity": None,
    "num_class": 55,
    "use_label_encoder": False,
}
