# name: Deploy to AWS ECR

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     env:
#       AWS_REGION: ${{ secrets.AWS_REGION }}
#       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Login to Amazon ECR
#         run: |
#           aws ecr get-login-password --region $AWS_REGION | \
#           docker login --username AWS --password-stdin \
#           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

#       - name: Build & Push Backend
#         run: |
#           docker build -t ml-backend ./backend
#           docker tag ml-backend:latest \
#           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ml-backend:latest
#           docker push \
#           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ml-backend:latest

#       - name: Build & Push Frontend
#         run: |
#           docker build -t ml-frontend ./frontend
#           docker tag ml-frontend:latest \
#           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ml-frontend:latest
#           docker push \
#           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ml-frontend:latest
